
## This playbook assumes you are installing Scylla using the same disks and NIC for all nodes ##


# Running all tasks all host group: ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook scylla_deployment.yml -i servers.ini
# -t / --tags only runs plays and tasks tagged with these values
# --skip-tags only runs plays and tasks whose tags do not match these values


# List all tasks: ansible-playbook scylla_deployment.yml --list-tasks

#playbook: scylla_deployment.yml
# play #1 (host_group_name_from_ini_file): host_group_name_from_ini_file                        TAGS: []
#   tasks:
#     Remove 'abrt' pkg from CentOS / RHEL                                                      TAGS: [1_prereq]
#     Install epel-release and wget pkgs on CentOS / RHEL                                       TAGS: [1_prereq]
#     Update apt cache on Debian / Ubuntu                                                       TAGS: [1_prereq]
#     Install add-apt-repository command utility on Debian / Ubuntu14                           TAGS: [1_prereq]
#     Add openjdk PPA to Ubuntu14 (prereq for Java 8)                                           TAGS: [2_java]
#     Add openjdk PPA to Debian (prereq for Java 8)                                             TAGS: [2_java]
#     Add Jessie-backports repo to Debian (prereq for Java 8)                                   TAGS: [2_java]
#     Update apt cache on Debian / Ubuntu                                                       TAGS: [2_java]
#     Install Java 8 on Ubuntu14, needed for Scylla release 1.7                                 TAGS: [2_java]
#     Install Java 8 on Debian, needed for Scylla release 1.7                                   TAGS: [2_java]
#     Select correct java version on Debian / Ubuntu14                                          TAGS: [2_java]
#     Download Scylla {{ release }} repo for Centos 7 / RHEL 7                                  TAGS: [3_repo]
#     Download Scylla {{ release }} repo for Ubuntu 14.04 (Trusty)                              TAGS: [3_repo]
#     Download Scylla {{ release }} repo for Ubuntu 16.04 (Xenial)                              TAGS: [3_repo]
#     Download Scylla {{ release }} repo for Debian 8 (Jessie)                                  TAGS: [3_repo]
#     Install scylla {{ release }} on Debian / Ubuntu                                           TAGS: [4_install]
#     Install scylla {{ release }} on CentOS / RHEL                                             TAGS: [4_install]
#     Configure Cluster name in yaml file                                                       TAGS: [5_conf]
#     Configure seeds in yaml file                                                              TAGS: [5_conf]
#     Configure listen address + rpc address in yaml file                                       TAGS: [5_conf]
#     Run Scylla Setup (RAID-0, XFS format, NIC queue, disk IOtune), this may take a while      TAGS: [5_conf]
#     Reboot server/s (required by Scylla)                                                      TAGS: [6_reboot]
#     Wait for server/s to come up from boot                                                    TAGS: [6_reboot]


# List all facts collected by ansible, on the host group: ansible -i servers.ini servers -m setup | less
# To filter specific facts use: -a "filter=ansible_distribution*"


---

- hosts: [host_group_name_from_ini_file]
  become: yes                                   # Run all tasks as root
  vars:
    release: 1.7                                # Scylla release to be installed
    cluster_name: cluster_name                  # Unique cluster name
    seeds: seed_node_ip                         # Need at least 1 live seed node for new nodes to join the cluster (use 1:3 ratio)
    disks: /dev/nvme0n1,/dev/nvme0n2            # Disk names for raid0 creation (comma seperated)
    NIC: eth0                                   # NIC to be used with optimized queue
  tasks:
    - name: Remove 'abrt' pkg from CentOS / RHEL
      yum: name=abrt state=absent
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
      tags:
       - 1_prereq
    - name: Install epel-release and wget pkgs on CentOS / RHEL
      yum: name={{ item }} state=latest
      with_items:
       - 1_prereq
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
      tags:
       - 1_prereq
    - name: Update apt cache on Debian / Ubuntu
      apt: update_cache=true
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' #and ansible_distribution_release == 'trusty')
      tags:
       - 1_prereq
    - name: Install add-apt-repository command utility on Debian / Ubuntu14
      package: name=software-properties-common state=present
      when: ansible_distribution == 'Debian' or (ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty')
      tags:
       - 1_prereq
    - name: Add openjdk PPA to Ubuntu14 (prereq for Java 8)
      apt_repository: repo="ppa:openjdk-r/ppa"
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'
      tags:
       - 2_java
    - name: Add openjdk PPA to Debian (prereq for Java 8)
      apt_repository: repo="ppa:openjdk-r/ppa" codename='trusty'
      when: ansible_distribution == 'Debian'
      tags:
       - 2_java
    - name: Add Jessie-backports repo to Debian (prereq for Java 8)
      apt_repository: repo="deb http://http.debian.net/debian jessie-backports main"
      when: ansible_distribution == 'Debian'
      tags:
       - 2_java
    - name: Update apt cache on Debian / Ubuntu
      apt: update_cache=true
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' #and ansible_distribution_release == 'trusty')
      tags:
       - 2_java
    - name: Install Java 8 on Ubuntu14, needed for Scylla release 1.7
      apt: name=openjdk-8-jre-headless state=latest
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'
      tags:
       - 2_java
    - name: Install Java 8 on Debian, needed for Scylla release 1.7
      apt: name=openjdk-8-jre-headless state=latest default_release=jessie-backports
      when: ansible_distribution == 'Debian'
      tags:
       - 2_java
    - name: Select correct java version on Debian / Ubuntu14
      alternatives: name=java path=/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
      when: ansible_distribution == 'Debian' or (ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty')
      tags:
       - 2_java
    - name: Download Scylla {{ release }} repo for Centos 7 / RHEL 7
      get_url: url=http://downloads.scylladb.com/rpm/centos/scylla-{{release}}.repo dest=/etc/yum.repos.d/scylla.repo
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
      tags:
       - 3_repo
    - name: Download Scylla {{ release }} repo for Ubuntu 14.04 (Trusty)
      get_url: url=http://downloads.scylladb.com/deb/ubuntu/scylla-{{release}}-trusty.list dest=/etc/apt/sources.list.d/scylla.list
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'
      tags:
       - 3_repo
    - name: Download Scylla {{ release }} repo for Ubuntu 16.04 (Xenial)
      get_url: url=http://downloads.scylladb.com/deb/ubuntu/scylla-{{release}}-xenial.list dest=/etc/apt/sources.list.d/scylla.list
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial'
      tags:
       - 3_repo
    - name: Download Scylla {{ release }} repo for Debian 8 (Jessie)
      get_url: url=http://downloads.scylladb.com.s3.amazonaws.com/deb/debian/scylla-1.7-jessie.list dest=/etc/apt/sources.list.d/scylla.list
      when: ansible_distribution == 'Debian'
      tags:
       - 3_repo
    - name: Install scylla {{ release }} on Debian / Ubuntu 
      package: name=scylla state=present force=yes
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
      tags:
       - 4_install
    - name: Install scylla {{ release }} on CentOS / RHEL
      package: name=scylla state=present
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
      tags:
       - 4_install
    - name: Configure Cluster name in yaml file
      shell: sed -i -- 's/Test Cluster/{{ cluster_name }}/g' /etc/scylla/scylla.yaml
      tags:
       - 5_conf
    - name: Configure seeds in yaml file
      shell: sed -i -- '/seeds/s/127.0.0.1/{{ seeds }}/g' /etc/scylla/scylla.yaml
      tags:
       - 5_conf
    - name: Configure listen address + rpc address in yaml file
      shell: sed -i -- "s/localhost/$(hostname -i)/g" /etc/scylla/scylla.yaml
      tags:
       - 5_conf
    - name: Run Scylla Setup (RAID-0, XFS format, NIC queue, disk IOtune), this may take a while
      shell: scylla_setup --disks {{ disks }} --nic {{ NIC }} --setup-nic
      tags:
       - 5_conf
    - name: Reboot server/s (required by Scylla)
      become: yes
      shell: sleep 2 && shutdown -r now "Ansible reboot"
      async: 1
      poll: 0
      ignore_errors: true
      tags:
       - 6_reboot
    - name: Wait for server/s to come up from boot
      local_action: wait_for host={{ inventory_hostname }} state=started port=22 delay=30 timeout=300 connect_timeout=60
      become: false
      tags:
       - 6_reboot
